name: Deploy Shopify Theme
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Shopify CLI
        run: |
          sudo npm i -g @shopify/cli @shopify/theme
          shopify version

      - name: Run Theme Check
        run: |
          gem install theme-check || true
          theme-check

      - name: Push to Unpublished Theme (Preview)
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          # Create unpublished preview theme and push
          shopify theme push --unpublished --json -s ${{ secrets.SHOPIFY_STORE }} \
            | tee push.json
          # Optional: auto-publish (REMOVE if you don't want auto go-live)
          # shopify theme publish -s ${{ secrets.SHOPIFY_STORE }} -f
