name: Deploy Shopify Theme

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for Shopify CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Shopify CLI
        run: |
          npm i -g @shopify/cli @shopify/theme
          shopify version

      - name: Run Theme Check
        run: |
          gem install theme-check || true
          theme-check || true

      - name: Push to Unpublished Preview Theme
        env:
          # ✅ Put your Theme Access token (starts with shptka_) in GitHub → Settings → Secrets → Actions
          # Name the secret: SHOPIFY_CLI_THEME_TOKEN
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          # Store domain for the CLI (I set your permanent myshopify domain from your screenshot)
          SHOPIFY_STORE: "3ce86d-e4.myshopify.com"
        run: |
          shopify theme push --unpublished -s "$SHOPIFY_STORE" --json | tee push.json
          echo "Preview theme pushed. Open the job logs for the preview URL."
